-- 코드를 작성해주세요
SELECT PARENT_ID AS ID, COUNT(*) AS CHILD_COUNT
FROM ECOLI_DATA
WHERE PARENT_ID IS NOT NULL
GROUP BY PARENT_ID

UNION ALL

SELECT ID , 0 AS CHILD_COUNT
FROM ECOLI_DATA
WHERE ID NOT IN (
    SELECT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)

ORDER BY 1;