-- 코드를 작성해주세요
SELECT ID, CASE
    WHEN CUME_DIST() over(ORDER BY SIZE_OF_COLONY) <= 0.25 THEN 'LOW'
    WHEN CUME_DIST() over(ORDER BY SIZE_OF_COLONY) <= 0.5 THEN 'MEDIUM'
     WHEN CUME_DIST() over(ORDER BY SIZE_OF_COLONY) <= 0.75 THEN 'HIGH'
      ELSE 'CRITICAL'
END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID;