SELECT A.ID, 
CASE 
WHEN B.COLONY_TILE = 1 then 'LOW'
WHEN B.COLONY_TILE = 2 then 'MEDIUM'
WHEN B.COLONY_TILE = 3 then 'HIGH'
else 'CRITICAL'
end as COLONY_NAME
FROM ECOLI_DATA A natural join (
    select ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY ASC) as COLONY_TILE
    FROM ECOLI_DATA
) B
order by 1 asc;