-- 코드를 작성해주세요
SELECT A.ID, CASE
    WHEN A.NTILE_RANK=1 THEN 'CRITICAL'
    WHEN A.NTILE_RANK=2 THEN 'HIGH'
    WHEN A.NTILE_RANK=3 THEN 'MEDIUM'
    ELSE 'LOW'
END as COLONY_NAME
FROM (
SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) as NTILE_RANK
FROM ECOLI_DATA) A
ORDER BY A.ID;