-- 코드를 작성해주세요
# PARENT -> CHILD 순서로 진화함
# RARITY가 RARE인 아이템을 PARENT로 갖는 아이템만 선택

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO JOIN ITEM_TREE USING (ITEM_ID)
WHERE PARENT_ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY='RARE'
)
ORDER BY ITEM_ID DESC;