# 대여 시작일이 2022-08 ~ 2022-10 인 것의 개수가 5회 이상인 자동차 ID
# 해당 기간 동안의 월별/ 자동차 ID별 / 총 대여 횟수
# 월 기준 오름 차순, 자동차 ID 기준 내림차순
# 특정 월의 총 대여 횟수가 0이면 결과에서 제외

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN ( 
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING COUNT(*)>=5
) AND MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY CAR_ID, MONTH(START_DATE)
ORDER BY MONTH(START_DATE), CAR_ID DESC;