-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN
(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
    WHERE DATE_FORMAT(A.START_DATE, '%Y-%m-%d') >= '2022-08-01' and DATE_FORMAT(A.START_DATE, '%Y-%m-%d') <= '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*)>=5
) AND MONTH(START_DATE) IN (
    SELECT MONTH(START_DATE)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    WHERE CAR_ID = B.CAR_ID
    GROUP BY MONTH(START_DATE)
    HAVING COUNT(*)>0
) AND DATE_FORMAT(START_DATE, '%Y-%m-%d') >= '2022-08-01' and DATE_FORMAT(START_DATE, '%Y-%m-%d') <= '2022-10-31'
GROUP BY CAR_ID, MONTH(START_DATE)
ORDER BY 1, 2 DESC;