# 특정 연도의 최대 대장균 정보를 담은 테이블을 따로 관리
SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, 
MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY as YEAR_DEV, ID
FROM ECOLI_DATA
order by 1, 2;