-- 코드를 작성해주세요
WITH MAXCOLONY AS (
SELECT MAX(SIZE_OF_COLONY) AS MAXCOLONY, YEAR(DIFFERENTIATION_DATE) as year
FROM ECOLI_DATA
GROUP BY year(DIFFERENTIATION_DATE)
)

SELECT YEAR(e.DIFFERENTIATION_DATE) as YEAR,
(m.maxcolony-e.size_of_colony) as YEAR_DEV,
e.id
FROM ECOLI_DATA as e
JOIN MAXCOLONY as m 
on year(e.DIFFERENTIATION_DATE)= m.year
ORDER BY 1, 2;
