-- 코드를 작성해주세요
SELECT F.ID, N.FISH_NAME, F.LENGTH
FROM FISH_INFO F JOIN FISH_NAME_INFO N ON (F.FISH_TYPE= N.FISH_TYPE)
WHERE LENGTH= (
    SELECT MAX(T.LENGTH)
    FROM FISH_INFO T
    WHERE F.FISH_TYPE= T.FISH_TYPE
)
ORDER BY 1;