-- 코드를 입력하세요
SELECT g.INGREDIENT_TYPE, g.TOTAL_ORDER
FROM (
    SELECT INGREDIENT_TYPE, sum(TOTAL_ORDER) as TOTAL_ORDER
    FROM FIRST_HALF NATURAL JOIN ICECREAM_INFO
    GROUP BY INGREDIENT_TYPE
) as g
ORDER BY g.TOTAL_ORDER;
