-- 코드를 작성해주세요
SELECT COUNT(*) as FISH_COUNT, MAX(LENGTH) as MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(
    CASE
        WHEN LENGTH IS NULL THEN 10
        ELSE LENGTH
    END
)>=33
ORDER BY FISH_TYPE;

--